In [1]:
import pandas as pd
data = pd.read_csv(r"C:\Users\SURYA MANOJ\OneDrive\Desktop\dataset\Student Depression Dataset.csv")
data

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33,Visakhapatnam,Student,5,0,8.97,2,0,5-6 hours,Healthy,B.Pharm,Yes,3,1.0,No,1
1,8,Female,24,Bangalore,Student,2,0,5.90,5,0,5-6 hours,Moderate,BSc,No,3,2.0,Yes,0
2,26,Male,31,Srinagar,Student,3,0,7.03,5,0,Less than 5 hours,Healthy,BA,No,9,1.0,Yes,0
3,30,Female,28,Varanasi,Student,3,0,5.59,2,0,7-8 hours,Moderate,BCA,Yes,4,5.0,Yes,1
4,32,Female,25,Jaipur,Student,4,0,8.13,3,0,5-6 hours,Moderate,M.Tech,Yes,1,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27,Surat,Student,5,0,5.75,5,0,5-6 hours,Unhealthy,Class 12,Yes,7,1.0,Yes,0
27897,140686,Male,27,Ludhiana,Student,2,0,9.40,3,0,Less than 5 hours,Healthy,MSc,No,0,3.0,Yes,0
27898,140689,Male,31,Faridabad,Student,3,0,6.61,4,0,5-6 hours,Unhealthy,MD,No,12,2.0,No,0
27899,140690,Female,18,Ludhiana,Student,5,0,6.88,2,0,Less than 5 hours,Healthy,Class 12,Yes,10,5.0,No,1
27900,140699,Male,27,Patna,Student,4,0,9.24,1,0,Less than 5 hours,Healthy,BCA,Yes,2,3.0,Yes,1

## DATA PREPROCESSING

In [2]:
data.isnull()
data['Financial Stress'] = data['Financial Stress'].fillna(data['Financial Stress'].mean())

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  object
 2   Age                                    27901 non-null  int64
 3   City                                   27901 non-null  object
 4   Profession                             27901 non-null  object
 5   Academic Pressure                      27901 non-null  int64
 6   Work Pressure                          27901 non-null  int64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  int64
 9   Job Satisfaction                       27901 non-null  int64
 10  Sleep Duration                         27901 non-null  object
 11  Dietary Habits                         27901 non-null  object
 12  Degree                                 27901 non-null  object
 13  Have you ever had suicidal thoughts ?  27901 non-null  object
 14  Work/Study Hours                       27901 non-null  int64
 15  Financial Stress                       27901 non-null  float64
 16  Family History of Mental Illness       27901 non-null  object
 17  Depression                             27901 non-null  int64
dtypes: float64(2), int64(8), object(8)
memory usage: 3.8+ MB

In [4]:
data = data.drop(['id','Profession','Work Pressure','Job Satisfaction','City'],axis =1)
data

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Male,33,5,8.97,2,5-6 hours,Healthy,B.Pharm,Yes,3,1.0,No,1
1,Female,24,2,5.90,5,5-6 hours,Moderate,BSc,No,3,2.0,Yes,0
2,Male,31,3,7.03,5,Less than 5 hours,Healthy,BA,No,9,1.0,Yes,0
3,Female,28,3,5.59,2,7-8 hours,Moderate,BCA,Yes,4,5.0,Yes,1
4,Female,25,4,8.13,3,5-6 hours,Moderate,M.Tech,Yes,1,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,Female,27,5,5.75,5,5-6 hours,Unhealthy,Class 12,Yes,7,1.0,Yes,0
27897,Male,27,2,9.40,3,Less than 5 hours,Healthy,MSc,No,0,3.0,Yes,0
27898,Male,31,3,6.61,4,5-6 hours,Unhealthy,MD,No,12,2.0,No,0
27899,Female,18,5,6.88,2,Less than 5 hours,Healthy,Class 12,Yes,10,5.0,No,1
27900,Male,27,4,9.24,1,Less than 5 hours,Healthy,BCA,Yes,2,3.0,Yes,1

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender'])
data['Sleep Duration'] = le.fit_transform(data['Sleep Duration'])
data['Dietary Habits'] = le.fit_transform(data['Dietary Habits'])
data['Degree']= le.fit_transform(data['Degree'])
data['Have you ever had suicidal thoughts ?'] = le.fit_transform(data['Have you ever had suicidal thoughts ?'])
data['Family History of Mental Illness'] = le.fit_transform(data['Family History of Mental Illness'])
data

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,1,33,5,8.97,2,0,0,3,1,3,1.0,0,1
1,0,24,2,5.90,5,0,1,10,0,3,2.0,1,0
2,1,31,3,7.03,5,2,0,5,0,9,1.0,1,0
3,0,28,3,5.59,2,1,1,7,1,4,5.0,1,1
4,0,25,4,8.13,3,0,1,17,1,1,1.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,0,27,5,5.75,5,0,3,11,1,7,1.0,1,0
27897,1,27,2,9.40,3,2,0,25,0,0,3.0,1,0
27898,1,31,3,6.61,4,0,3,22,0,12,2.0,0,0
27899,0,18,5,6.88,2,2,0,11,1,10,5.0,0,1
27900,1,27,4,9.24,1,2,0,7,1,2,3.0,1,1

In [6]:
x = data.drop(['Depression'],axis = 1)
x

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,1,33,5,8.97,2,0,0,3,1,3,1.0,0
1,0,24,2,5.90,5,0,1,10,0,3,2.0,1
2,1,31,3,7.03,5,2,0,5,0,9,1.0,1
3,0,28,3,5.59,2,1,1,7,1,4,5.0,1
4,0,25,4,8.13,3,0,1,17,1,1,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
27896,0,27,5,5.75,5,0,3,11,1,7,1.0,1
27897,1,27,2,9.40,3,2,0,25,0,0,3.0,1
27898,1,31,3,6.61,4,0,3,22,0,12,2.0,0
27899,0,18,5,6.88,2,2,0,11,1,10,5.0,0
27900,1,27,4,9.24,1,2,0,7,1,2,3.0,1

In [7]:
y = data['Depression']
y

0        1
1        0
2        0
3        1
4        0
        ..
27896    0
27897    0
27898    0
27899    1
27900    1
Name: Depression, Length: 27901, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [9]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
x_train, y_train = smote.fit_resample(x_train, y_train)

In [10]:
print(x_train)

       Gender  Age  Academic Pressure      CGPA  Study Satisfaction  \
0           1   30                  1  5.110000                   3
1           0   30                  4  9.600000                   2
2           1   28                  1  9.050000                   4
3           0   23                  5  9.660000                   1
4           1   34                  1  9.560000                   2
...       ...  ...                ...       ...                 ...
26219       0   20                  5  5.588678                   2
26220       0   19                  4  7.225340                   4
26221       0   33                  1  9.216422                   1
26222       1   27                  1  6.526178                   3
26223       1   23                  1  9.284300                   4

       Sleep Duration  Dietary Habits  Degree  \
0                   1               3      22
1                   2               1       1
2                   3               3      16
3                   1               0       9
4                   1               3      21
...               ...             ...     ...
26219               1               1      11
26220               1               0      11
26221               1               0      15
26222               0               1      21
26223               0               0      10

       Have you ever had suicidal thoughts ?  Work/Study Hours  \
0                                          1                 8
1                                          1                 4
2                                          0                 0
3                                          1                12
4                                          0                 3
...                                      ...               ...
26219                                      0                 7
26220                                      0                 5
26221                                      0                 8
26222                                      1                 2
26223                                      0                 6

       Financial Stress  Family History of Mental Illness
0              4.000000                                 1
1              5.000000                                 1
2              2.000000                                 1
3              5.000000                                 1
4              3.000000                                 0
...                 ...                               ...
26219          1.306377                                 0
26220          1.019072                                 0
26221          2.000000                                 1
26222          2.448213                                 0
26223          2.774849                                 0

[26224 rows x 12 columns]

In [11]:
print(x_test)

       Gender  Age  Academic Pressure  CGPA  Study Satisfaction  \
26688       1   21                  1  5.46                   1
25025       1   28                  5  7.09                   4
15342       0   18                  5  8.25                   2
24778       1   29                  3  8.21                   3
12706       1   33                  1  7.88                   3
...       ...  ...                ...   ...                 ...
21557       1   33                  5  9.97                   2
20107       0   26                  1  9.11                   3
7909        0   33                  5  5.42                   5
10040       1   30                  5  7.10                   1
24187       0   29                  3  5.57                   2

       Sleep Duration  Dietary Habits  Degree  \
26688               3               3      21
25025               1               0      19
15342               2               1      11
24778               1               3       2
12706               3               1      15
...               ...             ...     ...
21557               1               1      13
20107               1               0      18
7909                3               1      21
10040               2               3       5
24187               0               1       5

       Have you ever had suicidal thoughts ?  Work/Study Hours  \
26688                                      0                 0
25025                                      1                 6
15342                                      0                10
24778                                      0                11
12706                                      0                10
...                                      ...               ...
21557                                      0                 9
20107                                      0                 4
7909                                       0                 8
10040                                      1                 6
24187                                      1                11

       Financial Stress  Family History of Mental Illness
26688               5.0                                 1
25025               3.0                                 0
15342               5.0                                 1
24778               1.0                                 1
12706               4.0                                 0
...                 ...                               ...
21557               3.0                                 0
20107               4.0                                 1
7909                1.0                                 1
10040               3.0                                 0
24187               1.0                                 0

[5581 rows x 12 columns]

In [12]:
print(y_train)

0        0
1        1
2        0
3        1
4        0
        ..
26219    0
26220    0
26221    0
26222    0
26223    0
Name: Depression, Length: 26224, dtype: int64

In [13]:
print(y_test)

26688    0
25025    0
15342    1
24778    0
12706    0
        ..
21557    1
20107    0
7909     1
10040    1
24187    0
Name: Depression, Length: 5581, dtype: int64

In [14]:
import xgboost as xgb
xgb_model = xgb.XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
xgb_model.fit(x_train, y_train)

AttributeError: 'super' object has no attribute '__sklearn_tags__'

AttributeError: 'super' object has no attribute '__sklearn_tags__'

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, random_state=42, ...)

In [15]:
xgb_predictions = xgb_model.predict(x_test)
print(xgb_predictions)

[0 1 1 ... 0 1 1]

In [16]:
from sklearn.metrics import accuracy_score
xgbas = accuracy_score(y_test,xgb_predictions)
xgbas

0.8389177566744311

In [ ]:
import pickle
with open('xgb_model.pkl', 'wb') as file:
    pickle.dump(xgb_model, file)

In [ ]:
with open('xgb_model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

In [ ]:
# Taking input from the user with corrected syntax and formatting
Gender = int(input("Enter the Gender \n 'Female': 0 \n 'Male': 1\n"))
Age = float(input("Enter the Age: "))
Academic_Pressure = float(input("Enter the Academic Pressure: "))
CGPA = float(input("Enter the CGPA: "))
Study_Satisfaction = float(input("Enter the Study Satisfaction: "))
Sleep_Duration = int(input("\nEnter the Sleep Duration\n '5-6 hours': 0 \n '7-8 hours': 1 \n 'Less than 5 hours': 2\n 'More than 8 hours' : 3"))
Dietary_Habits = int(input("\nEnter the Dietary Habits \n 'Healthy': 0 \n 'Moderate': 1 \n 'Unhealthy': 2\n"))
Degree = int(input("Enter Your Degree \n 'B.Pharm': 0 \n 'BA': 1 \n 'BCA': 2 \n 'BSc': 3 \n 'Class 12': 4 \n 'M.Tech': 5 \n 'MD': 6 \n 'MSc': 7\n"))
Suicidal_Thoughts = int(input("Enter if you have ever had suicidal thoughts \n 'No': 0 \n 'Yes': 1\n"))
Work_Study_Hours = float(input("Enter Work/Study Hours: "))
Financial_Stress = float(input("Enter the Financial Stress: "))
Family_History_Mental_Illness = int(input("Enter Family History of Mental Illness \n 'No': 0 \n 'Yes': 1\n"))

# Displaying the collected data
print("\nCollected Data:")
print(f"Gender: {Gender}")
print(f"Age: {Age}")
print(f"Academic Pressure: {Academic_Pressure}")
print(f"CGPA: {CGPA}")
print(f"Study Satisfaction: {Study_Satisfaction}")
print(f"Sleep Duration: {Sleep_Duration}")
print(f"Dietary Habits: {Dietary_Habits}")
print(f"Degree: {Degree}")
print(f"Suicidal Thoughts: {Suicidal_Thoughts}")
print(f"Work/Study Hours: {Work_Study_Hours}")
print(f"Financial Stress: {Financial_Stress}")
print(f"Family History of Mental Illness: {Family_History_Mental_Illness}")

'''
  539	Female	24	Kolkata	Student	5	0	8.96	1	0	5-6 hours	Moderate	BCA	Yes	12	5	No	1
'''

In [ ]:
import numpy as np
input_data = np.array([[
    Gender,
    Age,
    Academic_Pressure,
    CGPA,
    Study_Satisfaction,
    Sleep_Duration,
    Dietary_Habits,
    Degree,
    Suicidal_Thoughts,
    Work_Study_Hours,
    Financial_Stress,
    Family_History_Mental_Illness
]])

# Make a prediction
prediction = clf_model.predict(input_data)
prediction_prob = clf_model.predict_proba(input_data)

# Display the results
print("\nPrediction Result:")
if prediction[0] == 1:
    print("The model predicts: The Students Mental Health is not good")
else:
    print("The model predicts: The Students Mental Health is  good")

print("\nPrediction Probability:")
print(f"Probability of Having Good Mental Health : {prediction_prob[0][0]:.2f}")
print(f"Probability of Not Having the Good Mental Health: {prediction_prob[0][1]:.2f}")